/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class AskQuestionSetNumberOfContextDocsRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "numberOfDocumentsInContext" })
    numberOfDocumentsInContext?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "query" })
    query?: string;
}

export class AskQuestionSetNumberOfContextDocsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
