/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class HttpLocalhost3000ApiScansitemapRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "rootDomain" })
    rootDomain?: string;
}

export class HttpLocalhost3000ApiScansitemapResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
