/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class IngestTextWithMetadataRequestBodyMetadata extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "externalId" })
    externalId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "source" })
    source?: string;
}

export class IngestTextWithMetadataRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => IngestTextWithMetadataRequestBodyMetadata)
    metadata?: IngestTextWithMetadataRequestBodyMetadata;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "partition" })
    partition?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "text" })
    text?: string;
}

export class IngestTextWithMetadataResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
